### ISSUE TITLE
how does the cls information added at the first of image

### ISSUE THREAD

**Issue by SKY072410** [Theia-4869/FasterVLM#1]
Thank you for your good job.I want to know how CLS attention is added at the beginning of an image.and I want to know exactly what CLS is？Is CLS a self set action category？Thank you for your answer.
![1](https://github.com/user-attachments/assets/54bf526b-187b-4d4d-b511-7f55b6c6753d)

**Comment by Theia-4869** [comment]
Thank you for your interest in our work. In our study, CLS attention refers to the attention scores of the [CLS] token in CLIP over all image patch tokens. The [CLS] token is a special token that represents global information about the input image and is widely used in vision transformers like CLIP. This token is concatenated with all the patch tokens after patch embedding, as shown below:

$z_0 = [x_{\text{CLS}}; x_p^1E; x_p^2E; ... ; x_p^NE] + E_{pos}$

By the way, our preprint paper and project page are coming soon. If you are interested, please stay tuned!☺️

**Comment by SKY072410** [comment]
Thank you for your answer.

**Comment by Theia-4869** [comment]
The links of our preprint paper and project page have been updated, featuring diagrams and demonstration videos to provide a clearer presentation of our work. Feel free to take a look!🥳
