### ISSUE TITLE
Differences between FasterVLM and LLaVA-PurMerge

### ISSUE THREAD

**Issue by xinlong-yang** [Theia-4869/FasterVLM#2]
Thanks for your great work, I want to know the idea that using [cls] token in ViT to prune visual token is similar to LLaVA-PurMerge, what are the differences between them?

**Comment by Theia-4869** [comment]
Thanks for your interest in our work.😊 The main contributions of our work, as well as the differences from LLaVA-PurMerge, are summarized as follows:

1. We identify the **inaccurate visual-text attention** within the LLM decoder of VLMs and explain it from two perspectives of _**attention shift**_ and _**attention dispersion**_, analyzing the relevant reasons.  
2. Our work focuses on **training-free** VLM inference acceleration and highlights that some techniques that perform well during training **do not show significant benefits** in training-free scenarios.

More specifically, as demonstrated in our ablation studies, operations such as token merging do not improve performance in training-free settings and may even lead to performance degradation. In contrast, LLaVA-PurMerge primarily targets scenarios requiring further training. Our empirical evaluation shows that it performs poorly in training-free conditions. Below is a comparison between our FasterVLM and LLaVA-PurMerge under the LLaVA-1.5-7B model:  

| Method          | Reduction Ratio | \# Token |  VQAv2 |   GQA  | VisWiz | SQA-IMG | TextVQA |  POPE  |    MME   |   MMB  | MMB-CN | MM-Vet | Average |
|-----------------|:---------------:|:--------:|:------:|:------:|:------:|:-------:|:-------:|:------:|:--------:|:------:|:------:|:------:|:-------:|
| LLaVA-1.5-7B    |        0%       |    576   | 78.52  | 61.94  | 50.06  |  69.51  |  58.21  | 85.87  | 1506.47  | 64.69  | 58.08  | 31.30  | 100.00% |
| LLaVA-PruMerge  |       25%       |    432   | 77.06  | 59.06  | 51.37  |  68.37  |  55.21  | 85.60  | 1459.46  | 63.49  | 56.53  | 33.10  |  98.71% |
| LLaVA-PruMerge+ |       25%       |    432   | 77.04  | 59.35  | 50.88  |  67.77  |  55.43  | 84.33  | 1484.42  | 63.66  | 58.25  | 31.20  |  98.34% |
| FasterVLM       |       25%       |    432   | 78.39  | 61.51  | 50.01  |  68.57  |  57.91  | 85.92  | 1501.10  | 65.12  | 58.51  | 32.40  | 100.18% |
| LLaVA-PruMerge  |       50%       |    288   | 75.60  | 57.21  | 52.03  |  69.16  |  55.16  | 81.63  | 1423.53  | 62.29  | 56.53  | 35.00  |  98.18% |
| LLaVA-PruMerge+ |       50%       |    288   | 75.15  | 57.69  | 52.44  |  69.31  |  55.26  | 81.08  | 1396.86  | 61.17  | 56.87  | 29.40  |  96.18% |
| FasterVLM       |       50%       |    288   | 77.86  | 60.64  | 50.45  |  68.37  |  57.90  | 86.20  | 1471.96  | 63.83  | 56.70  | 34.80  | 100.12% |
| LLaVA-PruMerge  |       75%       |    144   | 74.70  | 56.79  | 52.44  |  68.77  |  54.92  | 79.56  | 1389.63  | 61.43  | 55.67  | 32.10  |  96.31% |
| LLaVA-PruMerge+ |       75%       |    144   | 74.66  | 57.61  | 53.41  |  69.26  |  54.99  | 81.18  | 1420.50  | 60.40  | 54.98  | 29.50  |  96.00% |
| FasterVLM       |       75%       |    144   | 76.19  | 58.34  | 51.97  |  67.92  |  57.07  | 83.46  | 1433.76  | 62.54  | 57.13  | 34.20  |  98.75% |
| LLaVA-PruMerge  |       90%       |    58    | 71.05  | 54.08  | 53.52  |  69.31  |  54.52  | 71.71  | 1316.01  | 59.71  | 53.52  | 28.20  |  92.35% |
| LLaVA-PruMerge+ |       90%       |    58    | 71.25  | 55.35  | 54.32  |  69.01  |  53.63  | 74.85  | 1328.35  | 59.79  | 52.75  | 28.90  |  93.09% |
| FasterVLM       |       90%       |    58    | 71.92  | 54.91  | 53.01  |  68.91  |  55.28  | 75.85  | 1348.63  | 60.57  | 54.90  | 30.10  |  94.24% |
| LLaVA-PruMerge  |       95%       |    29    | 65.70  | 50.91  | 52.94  |  69.56  |  52.05  | 62.91  | 1265.30  | 56.62  | 49.05  | 23.80  |  86.64% |
| LLaVA-PruMerge+ |       95%       |    29    | 65.44  | 52.27  | 52.93  |  68.57  |  51.65  | 67.54  | 1198.16  | 54.98  | 45.96  | 24.10  |  86.01% |
| FasterVLM       |       95%       |    29    | 66.75  | 51.51  | 52.67  |  69.56  |  53.09  | 67.24  | 1254.80  | 58.51  | 51.98  | 27.50  |  89.41% |

Our proposed FasterVLM is simple yet effective, and we hope this work provides some insights into understanding the interactions between visual inputs and language instructions in VLMs. Further exploration of this part is also ongoing as our future work.
