### ISSUE TITLE
About Video-LLaVA

### ISSUE THREAD

**Issue by nonomanlurker** [Theia-4869/FasterVLM#3]
Thank you for your work. 
I was wondering if there is any chance to open-source video-related tasks. 
Thank you!

**Comment by Theia-4869** [comment]
Thanks for your interest in our work. Our FasterVLM with [Video-LLaVA](https://github.com/PKU-YuanGroup/Video-LLaVA) has been released at the [video](https://github.com/Theia-4869/FasterVLM/tree/video) branch. Feel free to check it out, and if you have any further questions, please don't hesitate to ask! 😁
