### ISSUE TITLE
About Visualization Result

### ISSUE THREAD

**Issue by KaKa-101** [Theia-4869/FasterVLM#5]
Hi, thanks a lot for your great work. I want to ask how to get the [CLS] and last attention map in the first row of Fig.4. Could you provide a script for this visualization or tell me how to do it?

**Comment by Theia-4869** [comment]
Thanks for your interest in our work. To obtain the [CLS] and last attention maps, you can easily make minor adjustments to the `llava/eval/analyze_attn_dispersion.py`. Specifically, at [L132-133](https://github.com/Theia-4869/FasterVLM/blob/main/llava/eval/analyze_attn_dispersion.py#L132#L133) of the file, you should already get two tensors, `cls_attn` and `last_attn`, with a shape of `(1, 576)`. You can reshape them into `(1, 24, 24)` and use matplotlib for colormap visualization. 

For example:

```python

# Assume cls_attn and last_attn are tensors with shape (1, 576)
cls_attn_map = cls_attn.reshape(1, 24, 24)[0]
last_attn_map = last_attn.reshape(1, 24, 24)[0]

# Visualize the [CLS] attention map
plt.figure(figsize=(6, 6))
plt.imshow(cls_attn_map, cmap='viridis')
plt.axis('off')
plt.title("[CLS] Attention Map")
plt.tight_layout()
plt.savefig("cls_attn_map.png")

# Visualize the last attention map
plt.figure(figsize=(6, 6))
plt.imshow(last_attn_map, cmap='viridis')
plt.axis('off')
plt.title("Last Attention Map")
plt.tight_layout()
plt.savefig("last_attn_map.png")
```

Let us know if you have further questions! 😉
